api_platform:
    title: jorge07/symfony-5-es-cqrs-boilerplate
    description: Symfony 5 DDD ES CQRS backend boilerplate
    version: 1.0.0

    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            Bearer:
                name: Bearer
                type: header
    # Even if not used, it enables API Platform filters for elasticsearch
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
