api_platform:
    title: jorge07/symfony-5-es-cqrs-boilerplate
    description: Symfony 5 DDD ES CQRS backend boilerplate
    version: 1.0.0

    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            Bearer:
                name: Bearer
                type: header
    # Even if not used, it enables API Platform filters for elasticsearch
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
        
    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: 400
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Custom mapping
        App\Domain\Shared\Query\Exception\NotFoundException: 404
        App\Domain\User\Exception\InvalidCredentialsException: 401
        App\Domain\User\Exception\ForbiddenException: 403
        Broadway\Repository\AggregateNotFoundException: 404
        App\Domain\User\Exception\EmailAlreadyExistException: 409
        
        # Fallback    
        InvalidArgumentException: 400
