services:
    ## Custom filters
    
    App\Infrastructure\Bridge\ApiPlatform\Elasticsearch\Filter\RangeFilter:
        abstract: true
        autowire: true
        autoconfigure: true

    ## Filters applied to collection operations
    
    events.type_filter:
        parent: 'api_platform.elasticsearch.match_filter'
        arguments: [ { type: ~ }]
        tags:  [ 'api_platform.filter' ]
    
    events.occured_on_filter:
        parent: App\Infrastructure\Bridge\ApiPlatform\Elasticsearch\Filter\RangeFilter
        arguments: 
            $properties: { occurredOn: ~ }
        tags:  [ 'api_platform.filter' ]
