# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
    - { resource: 'api_platform_filters.yaml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    elastic:
        hosts:
            - '%env(ELASTICSEARCH_HOST)%'

    env(ELASTICSEARCH_HOST): 'elasticsearch:9200'
    env(DATABASE_URL): 'mysql://root:api@mysql:3306/api?serverVersion=8.0'

    # Map domain events to serialization contexts.
    # This allows us to hook into Broadway serialization process.
    # Note that if a mapping doesn't exist, it will serialize the whole object.
    #
    # You'll need to create configuration file at config/serializer/your_config.yaml
    # in order to use defined groups
    #
    # @see \App\Infrastructure\Share\Serializer\BroadwaySerializer
    normalization_contexts: []
        # Example of event mapping to normalization process
        # App\Domain\User\Event\UserWasCreated:
        #     groups: [user_was_created, credentials_sensitive]

    denormalization_contexts: []
        # Example of event mapping to normalization process
        # App\Domain\User\Event\UserWasCreated:
        #     groups: [user_was_created, credentials_sensitive]

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $elasticConfig: '%elastic%'
            $eventBus: '@broadway.event_handling.event_bus'
            $eventStore: '@Broadway\EventStore\Dbal\DBALEventStore'
            array $normalizationContexts: '%normalization_contexts%'
            array $denormalizationContexts: '%denormalization_contexts%'

    _instanceof:
        App\Infrastructure\Share\Bus\Command\CommandHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }

        App\Infrastructure\Share\Bus\Query\QueryHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.query }

        App\Infrastructure\Share\Bus\Event\EventHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.event.async }

        Broadway\EventHandling\EventListener:
            public: true
            tags:
                - { name: broadway.domain.event_listener }

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Domain/*/Exception/*'
            - '../src/Infrastructure/Kernel.php'
            - '../src/Infrastructure/Share/Migrations'

#    App\Infrastructure\Share\Bus\Command\CommandBus:
#        arguments:
#            - '@messenger.bus.command'

#    App\Infrastructure\Share\Bus\Query\QueryBus:
#        arguments:
#            - '@messenger.bus.query'

    App\Bridge\ApiPlatform\DataProvider\QueryDataProvider:
        arguments:
            $dataTransformers: !tagged api_platform.data_transformer
        tags:
            # Before API Platform elasticsearch data provider
            - { name: api_platform.collection_data_provider, priority: 10 }

    App\Bridge\ApiPlatform\DataProvider\ElasticsearchDataProvider:
        arguments:
            $repositories: !tagged_locator { tag: infrastructure.repository.elasticsearch, index_by: 'resource_class' }
            $collectionExtensions: !tagged api_platform.elasticsearch.request_body_search_extension.collection
        tags:
            # Before API Platform elasticsearch data provider
            - { name: api_platform.collection_data_provider, priority: 8 }
    
    App\Application\Query\CollectionQueryFactory:
        arguments:
            $collectionOptions: '%api_platform.collection.pagination%'
    
    App\Bridge\ApiPlatform\Metadata\Property\Factory\NoPrefixPropertyMetadataFactory:
        decorates: api_platform.metadata.property.metadata_factory
        # Before api_platform.metadata.property.metadata_factory.serializer
        decoration_priority: 35
    
    App\Bridge\ApiPlatform\Metadata\Property\Factory\ValueObjectPropertyMetadataFactory:
        decorates: api_platform.metadata.property.metadata_factory
        # Before api_platform.metadata.property.metadata_factory.serializer
        decoration_priority: 34

    ### Event Store

    Broadway\EventStore\Dbal\DBALEventStore:
        public: true
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@App\Infrastructure\Share\Serializer\BroadwaySerializer'
            - '@App\Infrastructure\Share\Serializer\BroadwaySerializer'
            - 'events'
            - true
            - '@broadway.uuid.converter'
    
    ### Elasticsearch repository
    
    App\Infrastructure\Share\Event\Query\DomainEventElasticsearchRepository:
        tags:
            # Tag used by ElasticsearchDataProvider, a repository can support many resource_class
            # Add as many tags as necessary for all resource_class handled by this service
            - { name: infrastructure.repository.elasticsearch, resource_class: App\Domain\Shared\DomainEvent }
    
    ### Specification

    App\Domain\Shared\Specification\UniqueAggregateRootSpecification:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $tableName: 'events'

    ### Swagger decorators

    App\Bridge\ApiPlatform\Swagger\AuthSwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        autoconfigure: false

    App\Bridge\ApiPlatform\Swagger\HealthzSwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        autoconfigure: false

    ### UI

    App\UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller/*'
        tags: [ 'controller.service_arguments' ]

    App\UI\Http\Web\Controller\:
        resource: '../src/UI/Http/Web/Controller/*'
        tags: ['controller.service_arguments']
